logging:
  level:
    org:
      springframework:
        security: TRACE
spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:proposta
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      javax:
        persistence:
          query:
            timout: 50
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/nosso-cartao}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/nosso-cartao/protocol/openid-connect/certs}
feign:
  client:
    config:
      solicitacao:
        read-timeout: ${SOLICITACOES_READ_TIMEOUT:1000}
        connect-timeout: ${SOLICITACOES_CONNECT_TIMEOUT:1000}
      cartao:
        read-timeout: ${CARTOES_READ_TIMEOUT:1000}
        connect-timeout: ${CARTOES_CONNECT_TIMEOUT:1000}
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics, health, prometheus
    prometheus:
      enable: true
  metrics:
    export:
      prometheus:
        enable: true
    tags:
      aplicacao: ${NOME_DA_APLICACAO:proposta}
      ambiente: ${AMBIENTE:dev}
externo:
  solicitacao: ${SOLICITACOES_URL:http://localhost:9999/api/solicitacao}
  cartao: ${CARTOES_URL:http://localhost:8888/api/cartoes}
periodicidade:
  schendule:
    proposta-cartao: ${SCHENDULE_PROPOSTA_CARTAO:10000}
